export const FETCHING_JOB_DETAILS = 'FETCHING_JOB_DETAILS';
export const ERROR_JOB_DETAILS = 'ERROR_JOB_DETAILS';

export const EDIT_JOB_STATUS = 'EDIT_JOB_STATUS';

export const EDIT_JOB_DETAILS = 'EDIT_JOB_DETAILS';
export const GET_JOB_DETAILS = 'GET_JOB_DETAILS';
